//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bat.PortalDeCargas.Resource.Resources.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TemplateTranslation_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateTranslation_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bat.PortalDeCargas.Resource.Resources.Translation.TemplateTranslation.pt-BR", typeof(TemplateTranslation_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro removendo o template.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de arquivo não reconhecido.
        /// </summary>
        internal static string FileTypeInvalid {
            get {
                return ResourceManager.GetString("FileTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao obter os templates.
        /// </summary>
        internal static string GetFilteredError {
            get {
                return ResourceManager.GetString("GetFilteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao obter o template.
        /// </summary>
        internal static string GetTemplateByIdError {
            get {
                return ResourceManager.GetString("GetTemplateByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro salvando o tem plate.
        /// </summary>
        internal static string PostError {
            get {
                return ResourceManager.GetString("PostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço do blob deve ser uma URL válida.
        /// </summary>
        internal static string TemplateBlobUrlMustBeValidUrl {
            get {
                return ResourceManager.GetString("TemplateBlobUrlMustBeValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do template é obrigatória.
        /// </summary>
        internal static string TemplateDescriptionMustBeFilled {
            get {
                return ResourceManager.GetString("TemplateDescriptionMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não podem haver furos na ordem das colunas.
        /// </summary>
        internal static string TemplateDimensionOrderGap {
            get {
                return ResourceManager.GetString("TemplateDimensionOrderGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janela de atualização inválida.
        /// </summary>
        internal static string TemplateEndUploadWindowInvalid {
            get {
                return ResourceManager.GetString("TemplateEndUploadWindowInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de arquivo informado é inválido.
        /// </summary>
        internal static string TemplateFileFormatMustBeFilled {
            get {
                return ResourceManager.GetString("TemplateFileFormatMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do template é obrigatório.
        /// </summary>
        internal static string TemplateNameMustBeFilled {
            get {
                return ResourceManager.GetString("TemplateNameMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do template deve ser unico.
        /// </summary>
        internal static string TemplateNameMustBeUnique {
            get {
                return ResourceManager.GetString("TemplateNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email de notificação não é válido.
        /// </summary>
        internal static string TemplateNotificationEmailInvalid {
            get {
                return ResourceManager.GetString("TemplateNotificationEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mensagem de notificação é obrigatória.
        /// </summary>
        internal static string TemplateNotificationTextMustBeFilled {
            get {
                return ResourceManager.GetString("TemplateNotificationTextMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A periodicidade informada não é válida.
        /// </summary>
        internal static string TemplatePeriodicityInvalid {
            get {
                return ResourceManager.GetString("TemplatePeriodicityInvalid", resourceCulture);
            }
        }
    }
}
